# Site settings
title: Eatfit
email:
description: > # this means to ignore newlines until "baseurl:"
  Welcome to eatfit
subject: Nutrition and Fitness
repo: "https://github.com/ucdavis/eatfit-static"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eatfit.ucdavis.edu" # the base hostname & protocol for your site

break: md

permalink: pretty


# Build settings
markdown: kramdown

#gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - octopress-autoprefixer

# collections:
#   contents:
#     output: true
